server:
  port: 9300


spring:
  application:
    name: @artifactId@
#  boot:
#    admin:
#      client:
#        url: http://localhost:8769
#    #profiles: dev
#  cloud:
#    sentinel:
#      transport:
#        port: 8719
#        dashboard: localhost:8080

  # 配置邮件
  mail:
    host: smtp.163.com
    port:
    protocol: smtp
    username: jxaijm94@163.com
    password: ai123456

aliyun:
  oss:
    accessKeyId: 122
    accessKeySecret: 334
    bucketName: 445
    callback: 67
    endpoint: 789
    endpointInternal: 7899
    maxSize: 67889
    policyIexpire: 5677
    filePaths:
      - type: default
        prePath: default
        belongName: default
        belongType: default
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.cloud.auth.entity
  global-config:
    banner: false
    db-config:
      column-underline: true
      #capital-mode: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  performanceInterceptor:
    enabled: true

security:
  oauth2:
    resourceId: oss
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://cloud-auth/oauth/token
      user-authorization-uri: http://cloud-auth/oauth/authorize
      ignore-urls:
        - /v2/api-docs
        - /swagger-resources
        - /swagger-resources/**
        - /configuration/ui
        - /configuration/security
        - /swagger-ui.html
        - /webjars/**
    resource:
      token-info-uri: http://cloud-auth/oauth/check_token
      loadBalanced: true


swagger:
  enabled: true
  author: Hcloud
  title: Hcloud SpringCloud
  desc: Hcloud SpringCloud doc
  version: v2.0
  termsOfServiceUrl: http://www.eduvipx.cn/termsOfServiceUrl
  host: 127.0.0.1:9999
  authUri: http://127.0.0.1:9999/auth/oauth/token

logging:
  config: classpath:logback-spring.xml

info:
  name: @project.artifactId@
  description: @project.description@
  version: @project.version@
